### PR TITLE
Vertx 4.0 & Groovy 3.0

### PR DESCRIPTION
**Pull request by aaloise**
Version 1.7.1

### CODE REVIEW

**Comment by aaloise** [comment]
Changed the PR to upgrade Groovy version to 3.0 aiming Vert.x 4.0

Build passes at the moment with Groovy 3.0.0-beta-2, which is good. Let's see if build continues to succeed with the following versions until Groovy 3 hits GA

**Comment by aaloise** [comment]
Groovy 3.0.0-beta-3 also passes.

**Comment by vietj** [comment]
good, do you know when Groovy 3 will be released ?

**Comment by aaloise** [comment]
It has been speculated to be in late September. It is possible that the next version to be released will be the first RC.

Maybe Paul King announces some date in his webinar on August 27th.

https://objectcomputing.com/products/grails/resources/groovy-3-and-beyond

**Pull request merged**
