### PR TITLE
Update Groovy to 2.5.5

### PR DESCRIPTION
**Pull request by aaloise**

### CODE REVIEW

**Comment by aaloise** [comment]
Wrong PR. Please ignore.

**Comment by vietj** [comment]
@aaloise I would like actually to discuss groovy options for Vert.x 4 on the vertx-dev channel before doing any further, like what are the things we want to remove / change. Can you engage a conversation here ?

**Comment by aaloise** [comment]
@vietj sure, I can engage a conversation. But do you mean here, at github, or there, at the dev group?

**Comment by vietj** [comment]
the dev group

**Pull request closed without merging**
