### PR TITLE
Vertx 3.8.x & Groovy 2.5.x

### PR DESCRIPTION
**Pull request by aaloise**
Update version

### CODE REVIEW

**Comment by vietj** [comment]
CI does not seem to pass

**Comment by aaloise** [comment]
CI is taking too long to download dependencies. This has caused the builds to fail. When everything is downloaded, the build works.

Example: https://travis-ci.org/aaloise/vertx-lang-groovy/builds/569147158

**Comment by aaloise** [comment]
This one too passed.

https://travis-ci.org/aaloise/vertx-lang-groovy/builds/569336883

**Comment by aaloise** [comment]
Is there a way I can restart the build attempt without having to commit to the branch within my fork copy?

**Comment by vietj** [comment]
no, I can do it in the travis UI

**Comment by vietj** [comment]
I did it

**Pull request closed without merging**
