### PR TITLE
General improvements - Vert.x v4

### PR DESCRIPTION
**Pull request by aaloise**
This PR upgrades Groovy to 2.5.4, replaces FastClassPathScanner with ClassGraph, replaces some deprecated code and updates some of the tests code. Something migth have changed with Groovy (assumption), or maybe with Vert.x core code, because I spent a lot of time trying to adapt the test codes.

Unfortunately my efforts wasn't all enough. I got stuck in some test errors that, for some reason, doesn't work in Travis. I was hoping that someone could give a hand here, by reviewing the PR, and contribute to a solution.

Sorry not to be a 100% PR.

### CODE REVIEW

**Comment by aaloise** [comment]
I noticed that the nulls in CollectionTCKTest are because of TestDataObject. It's overrided equals method is not enough to do comparisions. For instance, the contains() method of a Set doesn't returns true for two equal objects, that's the reason is showing null.

TestObjectClass is annotated with @DataObject, so I guess the equals method is being generated at some point. Could it be an adjust to Vertx Codegen? Overriding hashCode would be helpfull to since the tests uses Sets.

**Comment by aaloise** [comment]
Opened https://github.com/vert-x3/vertx-codegen/issues/222 to request an update do equals() method of TestDataObject

**Comment by vietj** [comment]
this PR seems to go wider than just bumping the groovy version.

I can see the removal of the code generated vertx code and instead use Groovy-ish idioms like "as JsonObject" which is exactly what we want.

however I think we should split this in 2 efforts

- a groovy version bump for 3.6
- the improvements to groovy for 4.0

**Comment by vietj** [comment]
for 3.6 can you just make a groovy library version bump PR ? that's what we expect in this scope.

**Comment by aaloise** [comment]
@vietj that's what I was trying to do from the beginning , just bump groovy version to 2.5.x

But that brought some consequences, specially with tests codes. I spent a lot of time/days to adjust them and make the PR to build, which finally I manage to do.

The last commit was OK with build, so I leave to you to merge or to think a little more about in which way to go.

**Comment by aaloise** [comment]
Proposal: merge this PR to 3.6 and submit a new one to 4.0 when Groovy 3.x gets released.

**Comment by vietj** [comment]
this PR needs to be reviewed to check there are no breaking changes, it has a lot of changes and rewrites

**Comment by aaloise** [comment]
Fixes #57 and #62

**Comment by aaloise** [comment]
This PR seems useless after some changes made in master aiming Vert.x 4. I'm closing it.

**Pull request closed without merging**
