### PR TITLE
Update Groovy (Vert.x 4.5)

### PR DESCRIPTION
**Pull request by aaloise**
Groovy 4.0.13 -> 4.0.15

### CODE REVIEW

**Comment by tsegismont** [comment]
@aaloise can you investigate the test failure?

**Comment by aaloise** [comment]
@tsegismont it seems to be related to recent changes made to the Vertx class.

The signature of the method createHttpClient changed.

From ```HttpClient createHttpClient(HttpClientOptions options)``` to ```HttpClientPool createHttpClient(HttpClientOptions options);```

**Comment by aaloise** [comment]
Maybe a cache situation?

**Comment by tsegismont** [comment]
Maybe, these changes have been made to the main branch only to my knowledge.

Anyway, I'll go ahead and close this one, then merge #151

**Pull request closed without merging**
