### PR TITLE
Upgrade Groovy and Replace FastClasspathScanner

### LINKED ISSUE #57: Groovy 2.5
Apache Groovy 2.5 was recently released.

Consider to upgrade at the appropriate time.

Groovy 2.5 requires JDK8+ to build and JDK7 is the minimum version of the JRE that it supports.

### PR DESCRIPTION
**Pull request by aaloise**
This PR is intended to fix #57 and #62. Please review befor merge.

### CODE REVIEW

**Comment by vietj** [comment]
two tests don't pass

**Comment by aaloise** [comment]
Don't understand why. It's complaining about converting Map to JsonObject in ConversionTest. That's odd.

**Comment by vietj** [comment]
I don't know I haven't checked, how does it work for you locally ?

**Comment by aaloise** [comment]
Under investigation

**Comment by vietj** [comment]
is it making progress ?

**Comment by aaloise** [comment]
It is. Currently the failure are at the code lines that replaces FastClasspathScanner with ClassGraph in VertxExtensionMethodBoostrap. For some reason ExtensionModule module =(ExtensionModule) info.loadClass().getDeclaredConstructor().newInstance(); is getting null.

It should find io.vertx.groovy.codegen.testmodel.VertxExtensionModule but it's not. I open as issue at ClassGraph, cause maybe scaning is the problem. You can see the discussion here https://github.com/classgraph/classgraph/issues/265

**Comment by vietj** [comment]
what are you trying to do here with so many pushes ?

**Comment by aaloise** [comment]
Trying the identify what's wrong. Didn't realize that pushing to my own fork was getting reflected here. Perhaps is best to close this PR and open a new one when I get everything to work properly.

**Comment by vietj** [comment]
right :-) reopen when it works :-)

**Pull request closed without merging**
