### PR TITLE
Update to Groovy 2.5.4

### PR DESCRIPTION
**Pull request by aaloise**
As requested by @vietj , this is a PR that just upgrades Groovy to 2.5, so it can be merge in 3.6 branch

#64 is waiting for the best moment to be merged in master, targeting Vert.x 4

### CODE REVIEW

**Comment by vietj** [comment]
can you first make this PR on master and then we will port it to 3.6 branch

**Comment by vietj** [comment]
can you make a clean rebased contribution, it seems there are conflicts

**Comment by aaloise** [comment]
Done.

**Comment by aaloise** [comment]
Conflicts are resolved.

**Comment by vietj** [comment]
I can't merge using the UI, github still says there is a conflict.
screen shot 2018-12-05 at 22 12 11

**Comment by vietj** [comment]
just make a single commit PR (another) without any merge on master

**Comment by aaloise** [comment]
Is #67 what you meant ?

**Comment by aaloise** [comment]
I'm closing this one in favor of #67

**Pull request closed without merging**
