### PR TITLE
fix  NullPointerException at  VertxTransformation.java:171

### PR DESCRIPTION
**Pull request by aruis**
fix VertxTransformation  NullPointerException  when groovy lambda like {-> xxx;}

Signed-off-by: aruis <lovearuis@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
@aruis can you add a test ?

**Comment by aruis** [comment]
Let me try. @vietj

**Comment by aruis** [comment]
I update a test case. You'll see some error info before use my PR code.But the error info will not break test case.

**Comment by vietj** [comment]
it seems you are updating an existing test, could you instead add a new test with the actual test content ?

**Comment by vietj** [comment]
I've taken your patch but written another test and pushed a patch (https://github.com/vert-x3/vertx-lang-groovy/issues/46) . Thanks!

**Pull request closed without merging**
